# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy backend

on:
  push:
    branches:
      - master
    paths:
      - backend/EnergySavers.API/**
      - '!frontend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        working-directory: ./backend/EnergySavers.API
        run: dotnet build --configuration Release

      - name: dotnet publish
        working-directory: ./backend/EnergySavers.API
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/backend/EnergySavers.API/out

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/backend/EnergySavers.API/out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Generate required file
        run: echo ${{ secrets.SERVICE_ACCOUNT_KEY }} > options.json

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'energy-savers'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_91C0ECD76FD14321B0325B245AB04676 }}
          package: .
